### ISSUE TITLE
highlight.directive.ts

### ISSUE THREAD

**Issue by VZhyrytskiy** [akvitka/shop#3]
@HostListener('mouseenter') onMouseEnter() {
    this.backgroundColor = 'yellow';
  }
Можете объяснить почему этот код работает?

**Comment by akvitka** [comment]
Потому что переменная-мембер связана (декоратором @HostBinding) со свойством элемента, на котором применяется директива. Или вопрос подразумевает еще какие-то тонкости?

**Comment by VZhyrytskiy** [comment]
Я такой код увидел первый раз. Сначала хотел написать, что тут ошибка, но он работает. Если вывести this - то это экземпляр директивы. Вы на экземплре директивы создали свойство backgroundColor и почему-то при этом добавляется атрибут style и код работает. Вопрос почему? Может быть вы знаете.

Стандартній вариант это this.el.nativeElement.style.backgroundColor = 'yellow';

**Comment by VZhyrytskiy** [comment]
я уже увидел.
