### ISSUE TITLE
cart-item.model.ts

### ISSUE THREAD

**Issue by VZhyrytskiy** [akvitka/shop#4]
export class CartItem {
  constructor(public product: Product, public quantity: number) {
  }
}
Как вариант можно расширить модель продукта, добавив количество.

**Comment by akvitka** [comment]
В смысле, добавить и в продукт количество - и оставить в CartItem тоже, и перемножать?

Или в смысле можно было вместо того, чтобы добавлять в CartItem, можно было добавить в сам продукт? Если второе, то я думал об этом, но решил, что мой вариант с количеством в CartItem лучше - в плане инкапсуляции. Иначе пришлось бы менять это поле в исходном товаре, по мере того как юзер нащелкивает. А так, нащелканное количество с товаром не связано - и исходный продукт никак не меняется в процессе.

**Comment by VZhyrytskiy** [comment]
В модели продукта нет количества. Это ок. А вот в модели CartItem можно реализовать наследование от продукта с добавлением количества.

**Comment by akvitka** [comment]
А, в этом смысле. Понял.
Но тут уже поднимается большая и неоднозначная тема "Наследование vs. Включение" :)
Является ли CartItem товаром - или он содержит его?
Вроде как современные веяния склоняются ко все большему отказу от наследования, если только оно реально не необходимо. Типа всякой критики "хотели банан, а получили впридачу обезьяну и все джунгли с ней".
Могу переделать на наследование, но предпочел бы оставить в таком виде.

**Comment by VZhyrytskiy** [comment]
Без проблем.
